### PR TITLE
Switched admin to dracula theme 🧛🏻 

### PR DESCRIPTION
**Pull request by bmispelon**
Could be fun for halloween

### CODE REVIEW

**Comment by bmispelon** [comment]
@sjbitcode ping 😁

**Comment by sjbitcode** [comment]
wooohooo! 🦇 I'm already hearing dark pipe organ music 🎶 🧛‍♂️

**Comment by bmispelon** [comment]
Had to revert it, it seems it might not be compatible with the version of Django we're currently running (4.2) 😿

**Comment by bmispelon** [comment]
Oh wait, I deployed the revert and now the theme seems to be here 🤔 
(looks like something is off with our deployment scripts)

Is our website haunted now? 👻

**Comment by sjbitcode** [comment]
oh interesting, the theme should work with [Django 4.2 and above](https://github.com/sjbitcode/django-admin-dracula/blob/5b0233b1c85d39c17508f9ce0a1bf40ded7f6899/pyproject.toml#L37-L39) though

**Comment by bmispelon** [comment]
> oh interesting, the theme should work with [Django 4.2 and above](https://github.com/sjbitcode/django-admin-dracula/blob/5b0233b1c85d39c17508f9ce0a1bf40ded7f6899/pyproject.toml#L37-L39) though

That's good to know, thanks! I think this is a bug in our deployment scripts, I'm looking into it 👀

**Pull request merged**
