### PR TITLE
Added Pycharm banners for 2021 fundraiser.

### PR DESCRIPTION
**Pull request by carltongibson**
Refs 5aaf01b92f77ba5aee4c3b959538bf6603968d8b

### CODE REVIEW

**Comment by carltongibson** [comment]
@wsvincent Hiya. I think these are the required changes. 

Need confirmation on the URL, the `Until DATE`, and when we should make it live. 

Thanks!

**Comment by wsvincent** [comment]
Hi @carltongibson,

Here is the URL: https://www.jetbrains.com/pycharm/promo/support-django/
Until: April 29, 2021
Please make live as close to April 1, 2021 as you can.

Cheers mate!

**Comment by carltongibson** [comment]
Hey @wsvincent — thanks for the details. Updated and rebased now. 

> Please make live as close to April 1, 2021 as you can.

We'll see what we can do. 😉

**Review by felixxm — APPROVED** [review]
Thanks :+1:

**Comment by felixxm** [comment]
Merged & deployed.

**Comment by carltongibson** [comment]
Thanks @felixxm

**Comment by wsvincent** [comment]
Thanks @felixxm

**Pull request closed without merging**
