### PR TITLE
Clean Readme

### PR DESCRIPTION
**Pull request by kailashchoudhary11**

### CODE REVIEW

**Comment by pauloxnet** [comment]
Thanks can ask to check for other typos or error in the readme so that we can merge more than only one typo ? Have tried all the step in the readme for exmaple ?

**Comment by kailashchoudhary11** [comment]
> Thanks can ask to check for other typos or error in the readme so that we can merge more than only one typo ? Have tried all the step in the readme for exmaple ?

Okay I'm checking!

**Comment by kailashchoudhary11** [comment]
@pauloxnet In Running all at once section at 2nd bullet point should it be SCSS files instead of SASS files?

**Comment by kailashchoudhary11** [comment]
Done with it! Please review @pauloxnet .

**Comment by pauloxnet** [comment]
Thank @kailashchoudhary11 I merged this PR.

**Comment by kailashchoudhary11** [comment]
Thank you Sir! @pauloxnet

**Pull request merged**
