### PR TITLE
Fixed #1435 -- hamburger tab key focus issue fixed

### LINKED ISSUE #1435: When the "hamburger" menu is open, pressing the tab key for the first time should bring the focus to the first item in the menu list
When the menu is open, the first time we press the tab key, it should bring the focus to the first menu item on the list. Currently, it jumps to the light/dark theme button.

### PR DESCRIPTION
**Pull request by Bhagyarsh**
Issue #1435 

**Screenshots for reference**
Before:
before#1435

After:
after#1435

### CODE REVIEW

**Review by CuriousLearner — COMMENTED** [review]
Hey Bhagyarsh!

Thank you for your contribution.

This seems to flip the ordering of the dark-mode toggle with the hamburger menu option for me 🤔 albeit your screenshots do not show this.

I'm checking this on `Chrome Version 120.0.6099.109 (Official Build) (arm64)` on macOS. Can you please let me know which browser are you testing this on?

Before changes:

Screenshot 2023-12-16 at 11 51 00 PM

After Changes:

Screenshot 2023-12-16 at 11 53 10 PM

**Comment by Bhagyarsh** [comment]
Hi Sanyam,
 
I am using the same version of Chrome `google-chrome 120.0.6099.109-1 `. I am on a Linux machine.  I also checked it with Firefox `firefox 120.0.1-1`. I also tried clearing the cache and ordering of dark-mode toggle and the hamburger menu button looked fine for me.

Could it be a cache issue? Can you check it after clearing the cache, please? 
 
image

**Comment by Bhagyarsh** [comment]
Hi @CuriousLearner ,
I was wondering if you had a chance to review it further. Are there any changes required before merging it?
I'm happy to make any adjustments based on your feedback. Please let me know if you have any questions.
Thanks for your time, and I look forward to your response.
Best regards,

**Comment by bmispelon** [comment]
Hi @Bhagyarsh and thanks for this PR!

I took a look a it on my local version (using firefox) and your approach does seem to work (I did have to run `make compile-scss` after switching branches, maybe that's why the other commenter got the wrong behavior?).

However I'm a bit hesitant about adding more complexity to the HTML. Instead I tried an alternative approach and used `flex` for the layout of the whole header instead of floats. This lets the browser naturally focus things without having to add any extra HTML.
The result is in this PR: https://github.com/django/djangoproject.com/pull/1523
Can you tell me what you think?

Thanks! ✨

**Comment by bmispelon** [comment]
Hi, I ended up merging this feature in #1523. Thanks for being part of this team effort and working on improving the website 🚀

**Pull request closed without merging**
