### PR TITLE
Add anchor to DSF Supporters section

### PR DESCRIPTION
**Pull request by ipmb**
So we can link directly to it.

### CODE REVIEW

**Review by CuriousLearner — APPROVED** [review]
LGTM 🌮 

Though the build failed, but seems like an intermittent issue. 🤔

**Comment by CuriousLearner** [comment]
@carltongibson Can you please re-run the pre-commit CI? I'm not sure if I have that permission or how to do it. I see some recent PR's failing this check of some issue with `pyproject.toml`, though a lot of PR's to be merged into same commit on `main` shows that this check passes.

**Review by carltongibson — APPROVED** [review]
OK, I can't re-run the check. It's not related so... Onwards! 🚀

**Comment by carltongibson** [comment]
That's deployed https://www.djangoproject.com/fundraising/#dsf-supporters 💝

In other news though, the pre-commit error persists #1311 — something about poetry and isort. Gah.

**Pull request merged**
