### PR TITLE
Added PyCharm 2020 fundraiser banners.

### PR DESCRIPTION
**Pull request by frankwiles**
Hi there! 

We're going to be kicking off the 2020 PyCharm campaign today.  If you could merge this prior to 9am Pacific US time which if 5pm UTC I believe and get it deployed it would be greatly appreciated!

### CODE REVIEW

**Comment by felixxm** [comment]
@frankwiles Thanks :+1: I pushed small edits:

image
----
image
----
image

**Comment by frankwiles** [comment]
Awesome thanks! If I merge this will it deploy? If so I can handle that at the right time.

**Comment by ErnstHaagsman** [comment]
The date is wrong on this PR, should be March 14th.

**Comment by felixxm** [comment]
@frankwiles Can you confirm dates? PyCharm page is outdated :confused:  https://www.jetbrains.com/pycharm/promo/support-django/

**Comment by frankwiles** [comment]
@felixxm yep he's right, should be March 14th! I apparently didn't have enough coffee this morning

**Comment by felixxm** [comment]
Merged & deployed.

**Comment by frankwiles** [comment]
Thanks @felixxm !!!

**Pull request merged**
