### PR TITLE
Add Italian to docs translations

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by pauloxnet** [comment]
Related PR https://github.com/django/django-docs-translations/pull/29

**Comment by claudep** [comment]
Hey @carltongibson, @felixxm, tell me if you need more thumbs up, hearts,  rockets or hooray :smiling_face_with_three_hearts: 
Aaaah, Italian people, you rock!!

**Review by carltongibson — APPROVED** [review]
LGTM. 

@claudep I think we just need to create the matching elements in the admin and we'd be good. 🤔

**Comment by carltongibson** [comment]
https://github.com/django/django-docs-translations/commit/b3daca7c6922e7371881d314497e06953460e3de

**Comment by carltongibson** [comment]
OK, I'm going to merge this, and makes sure the matching bits are in play. Once deployed it may not appear _Instantly™_ IIRC but should build in the next period. 
Thanks all.

**Comment by claudep** [comment]
Thanks Carlton!

**Comment by pauloxnet** [comment]
Thanks @claudep and @carltongibson .

I've just published d an article about this PR:
https://www.paulox.net/2021/05/12/floss-and-linguistic-diversity/

**Comment by iflare3g** [comment]
Thanks so much @claudep , @carltongibson , @pauloxnet ! 🙏

**Comment by pauloxnet** [comment]
It's online
https://docs.djangoproject.com/it/3.2/

**Pull request merged**
