### PR TITLE
Made the surrounding div for the language and version chooser click-through

### PR DESCRIPTION
**Pull request by MarkusH**

### CODE REVIEW

**Comment by timgraham** [comment]
I think I understand what the intent is but I can't detect a behavior change on Firefox. Could you explain this a bit more?

**Comment by MarkusH** [comment]
The problem is that long items in a TOC of a documentation page may be underneath the language switcher which is notably smaller than the version switcher.

The div `#version-switcher` covers parts of the TOC. 
screenshot1

When you want to click a TOC link somewhere in that area the link is not clickable
screenshot2

With this change the `#version-chooser` has a click-through behavior and the `ul>li` tags have the normal behavior. The `ul` tags have the normal behavior when the `li` tags are hovered to allow for selection of the choices (otherwise the chooser would collapse when moving the mouse out of the current shown version)

**Comment by MarkusH** [comment]
Thanks for noticing, @timgraham. There was indeed some weird behavior with FF going on. Works for me, now.

**Comment by timgraham** [comment]
Looks good.

**Pull request merged**
