### PR TITLE
Remove Ruby Dependency, Switch to Libsass

### PR DESCRIPTION
**Pull request by mtrythall**
This removes the Ruby and Compass dependency and moves the project over to Libsass for Scss compilation. This is accomplished via the [Python Libsass package](https://pypi.python.org/pypi/libsass).

## Major changes:

1. Remove all ties to Compass. This was mostly the removal of mixins for vendor prefixing.
2. Replace vendor prefix mixins with the appropriate prefixed CSS. In some cases, like `border-radius`, there are none.
3. Compile the site using the new tools and test them against the matrix.
4. Add Libsass to the dev.txt requirements file.
5. Update `make` with the appropriate, new commands based on the Libsass (uses `sassc`).
6. Update the README to reflect some of these changes.

I did a few screenshot tests and the standard click-through testing for this sort of change. Here are a few screenshot tests:

* [Homepage](http://app.crossbrowsertesting.com/public/ic05b2f368a8ccf1/screenshots/zdaa6619f16ddde0f1a2)
* [Overview Page](http://app.crossbrowsertesting.com/public/ic05b2f368a8ccf1/screenshots/z457f8907d71ed180fbe)

I saw no issues but encourage another set of eyes spot check things.

This pull request does not include anything for deployment. Compiled CSS is still in the repo and the project is setup for compilation locally, only. This is easily changed, but I made no assumptions about deployment.

One side effect of this is that the watch functionality for Scss compilation is now split into standard and IE specific code as there are 2 primary Scss files: output.scss and output-ie.scss. This seemed like a minor loss given the gained functionality and speed.

Thanks to the LL team for their help here, specifically Peter Baumgartner for the other set of eyes.

### CODE REVIEW

**Comment by timgraham** [comment]
Could you advise on how to integrate the compile process with deployment?

**Comment by mtrythall** [comment]
@timgraham - I'll figure out WTF is up with my editor vs the config file and fix the formatting issues shortly. Thanks for taking a look!

**Comment by mtrythall** [comment]
@timgraham or anyone else, I think this is ready. Sorry for the formatting issues. Tabs in Scss is weird and I didn't notice.

**Comment by mtrythall** [comment]
> Could you advise on how to integrate the compile process with deployment?

I'm assuming you can just run `make compile-scss` as part of your deployment process and keep things as is, but I don't know enough about your deployment or general deployment of this sort of stuff to have strong advice.

**Comment by timgraham** [comment]
merged in 93d2663bfe1bed3fad21c34711255de98cae099d, thanks!

**Pull request closed without merging**
