### PR TITLE
Update Django 5.0

### PR DESCRIPTION
**Pull request by pauloxnet**
It seems that a test is failing after the upgrade

### CODE REVIEW

**Comment by bmispelon** [comment]
Ideally, we would also want to be running the same version of Django on both djangoproject.com and code.djangoproject.com (https://github.com/django/code.djangoproject.com).

That's because the two sites talk to the same database (Trac uses Django's user database for authentication), and that might break if for example a newer version of Django changes the user model.

**Comment by bmispelon** [comment]
Looks like Django 5.0 changed the way that `SimpleListFilter` processes its `params` argument. I didn't look into it, but it seems it now expects a dict that behaves like `request.GET` (where values are lists and not strings).

I've pushed a commit to the PR's branch that should fix the test suite 🤞🏻

**Comment by pauloxnet** [comment]
> Looks like Django 5.0 changed the way that `SimpleListFilter` processes its `params` argument. I didn't look into it, but it seems it now expects a dict that behaves like `request.GET` (where values are lists and not strings).
> 
> I've pushed a commit to the PR's branch that should fix the test suite 🤞🏻

Thanks for the fix and the explanation. :pray:

**Comment by pauloxnet** [comment]
> Ideally, we would also want to be running the same version of Django on both djangoproject.com and code.djangoproject.com (https://github.com/django/code.djangoproject.com).
> 
> That's because the two sites talk to the same database (Trac uses Django's user database for authentication), and that might break if for example a newer version of Django changes the user model.

I didn't know that, so I opened an issue over there:
https://github.com/django/code.djangoproject.com/issues/220

**Comment by pauloxnet** [comment]
> Looks like Django 5.0 changed the way that `SimpleListFilter` processes its `params` argument. I didn't look into it, but it seems it now expects a dict that behaves like `request.GET` (where values are lists and not strings).
> 
> I've pushed a commit to the PR's branch that should fix the test suite 🤞🏻

Sorry, I rebased to fix a requirements conflict and I dropped your commit, can you push it again?

**Comment by bmispelon** [comment]
> Sorry, I rebased to fix a requirements conflict and I dropped your commit, can you push it again?

Done (I think) 👍🏻

**Review by bmispelon — APPROVED** [review]

**Comment by bmispelon** [comment]
I think I'm ready to merge this (and https://github.com/django/code.djangoproject.com/pull/222).

The question that remains for me is whether this would be disruptive for the translation work @marksweb has been doing. Is it better to wait until all the translation PRs have been merged, or can we update Django now and deal with the consequences in the PRs afterwards?

**Comment by pauloxnet** [comment]
> The question that remains for me is whether this would be disruptive for the translation work @marksweb has been doing. Is it better to wait until all the translation PRs have been merged, or can we update Django now and deal with the consequences in the PRs afterwards?

I don't see how upgrading to Django 5.0 could be disruptive for the great internationalization work made by Mark.

BTW, this PR is a blocker for #1650 which would solve #1703, so I would merge this ASAP.

**Comment by pauloxnet** [comment]
I squashed the commits.

**Comment by marksweb** [comment]
@bmispelon I'm happy for this to merge & then I'll rebase my PRs. I can't see any conflicts occurring from this.

**Review by marksweb — APPROVED** [review]

**Comment by bmispelon** [comment]
> BTW, this PR is a blocker for #1650 which would solve #1703, so I would merge this ASAP.

I'll hope you allow me a bit of negativity here, but I find it frustrating seeing a comment like this. I've been doing my best reviewing PRs and fixing bugs in production on a site that has not effectively been maintained for years. Telling me something is urgent will not magically give me more free time, or more energy to work on this (quite the opposite in fact).

Plus the root causes of #1693 and #1703 have not been identified, so claiming that #1650 is going to fix them is wishful thinking at best.

I would find it more helpful if you explained what you did to make sure that this update would not break production for example. Did you run the test suite with the warnings on? Did you go through the removed features in the release notes and checked they didn't apply to us (what's the effect of dropping `USE_L10N` for example?).

**Comment by thibaudcolas** [comment]
@pauloxnet @bmispelon ❤️ let’s chat some time? I’d assume Paulo meant well and that he does hope (rightly or not) those changes would go towards fixing further issues. Plus the Django 5.0 changes are so good we’re all definitely very anxious and excited to get them for djangoproject.com! 😉 I’m certainly looking forward to all the accessibility improvements

**Comment by bmispelon** [comment]
Merged and deployed, the site is now running almost an up-to-date Django version, woohoo! 🎉 

Thanks for everyone who made it possible!

**Pull request merged**
