### PR TITLE
Remove the 2023 Django Developers Survey banner

### PR DESCRIPTION
**Pull request by glasnt**
Survey is now over!

Reverts django/djangoproject.com#1405

### CODE REVIEW

**Review by sabderemane — APPROVED** [review]
Thank you @glasnt ✨

**Comment by glasnt** [comment]
Thank @sabderemane! If this can be applied at your earliest convenience to remove the call to action banner from the website, that would be greatly appreciated.

**Comment by sabderemane** [comment]
@glasnt I don't have the rights to apply the changes but I've deferred that to people who should be able to :)

**Comment by felixxm** [comment]
Deployed.

**Pull request merged**
