### PR TITLE
fix #767 search field for page 404

### LINKED ISSUE #767: 404 page doesn't have search field
While reading the documentation there is useful field for search, just above "Support Django!" section. However when getting to 404 page, the field is not displayed. 

IMHO, the search field is widely used when getting to 404 page, so might be useful to add it.

### PR DESCRIPTION
**Pull request by oduvan**

### CODE REVIEW

**Comment by oduvan** [comment]
sorry, that was stupid, not to run all the tests before making pull-request

**Comment by oduvan** [comment]
the only issue with pull request is that 40* page doesn't show version number on placeholder, while any other page shows the version.

screen shot 2017-09-10 at 2 20 12 pm

**Comment by pauloxnet** [comment]
Is this PR still working with recent code changes ?

**Comment by oduvan** [comment]
should

**Comment by m-aciek** [comment]
@oduvan shouldn't it display the latest stable version and let search there?

**Comment by oduvan** [comment]
this pull-request is so old

**Comment by timgraham** [comment]
Closing due to inactivity.

**Pull request closed without merging**
