### PR TITLE
✨ Rework the community page to feature more modern resources more clearly

### PR DESCRIPTION
**Pull request by coderanger**
The community page centers older resources like the mailing list and IRC channel, which are no longer the best ways to participate in most parts of our community. You can skip down to the screenshots below but that main change is making a 2x2 grid of the primary calls to action to streamline those, as well as updates to the sidebar to remove deprecated or irrelevant content and generally update things.

Before (desktop view):

Screenshot 2022-12-14 at 12 32 22

After:
<details open>
  <summary>Desktop screenshot</summary>

Screenshot 2022-10-20 at 14-44-49 Django Community Django

</details>

<details>
  <summary>Mobile screenshot</summary>

Screenshot 2022-10-20 at 14-45-05 Django Community Django

</details>

### CODE REVIEW

**Comment by cgl** [comment]
Hi @coderanger, thanks for your PR.

Good set of changes, happy for it to go in with some tidy ups and tests 🚢 

Could you please add a before screenshot as well?

**Comment by coderanger** [comment]
<details>
<summary>Current desktop screenshot</summary>

Screenshot 2022-10-20 at 16-00-31 Django Community Django

</details>

As for tests, happy to add some but not sure what since there's no logic changes, this is only copy :)

**Comment by cgl** [comment]
I was referring to a UX QA, and maybe testing on different mobile devices.

**Comment by coderanger** [comment]
Ahh fair :D I posted a mobile screenshot for iOS 12/13 width just using Firefox's dev tools, but will see if I can get my phone to load the dev site directly for a more real test.

**Comment by coderanger** [comment]
<details>
<summary>Some real iOS screenshots</summary>

IMG_1718
IMG_1719
IMG_1720
</details>

**Comment by carltongibson** [comment]
I quite like this, FWIW. 🙂

**Comment by coderanger** [comment]
Anything I can do to help move this along?

**Comment by CuriousLearner** [comment]
This looks great, @coderanger !  Thank you for all your work! 🙏🏼 

Can you please rebase your PR agains the current main branch? Please tag me once you're done and I'll do a few tests before merging this in.

**Review by cgl — APPROVED** [review]
Looks good to me! Also tested locally 👍🏻

**Pull request merged**
