### PR TITLE
Ask donors whether they are donating as an individual or organization

### PR DESCRIPTION
**Pull request by ryankask**
This is for #383.

I've quickly worked something up with the goal of getting some feedback before proceeding.

First, Ola at the Django London Sprint suggested a radio select might look nice so I've used that. Also, I created a model field called `hero_type` with two choices but if there are only ever going to be 2 choices, an `is_organization` boolean would be better (or `is_individual`).

I'm happy to make any adjustments so please comment.

2015-03-22 at 12 34

### CODE REVIEW

**Comment by surfing-girl** [comment]
Hi guys, I'm working on issue https://github.com/django/djangoproject.com/issues/384. When do you plan to merge this pull request into branch fundraising-recurring?

**Comment by timgraham** [comment]
The code looks good. I rebased the `fundraising-recurring` branch to pickup the latest changes in master. Could you rebase your PR? Any test updates required? Could we add a new one?

**Comment by ryankask** [comment]
Sure, I'll rebase the branch. I didn't see any tests related the `thank_you` view but I'l create a new test case for it in the next day or two.

**Comment by ryankask** [comment]
I've updated the branch and added some tests. I added the tests in a separate commit since they weren't strictly related to the new feature.

Also, there was a stray pep8 violation that somehow wasn't picked up which I've corrected in a separate commit.

Please let me know if there are any issues.

@surfing-girl You're going to need to rebase your commit in #415. It wasn't a trivial rebase so I ended up using `cherry-pick` instead.

**Comment by timgraham** [comment]
Looks good. One more rebase please. CSS files are now removed from the repo, so this should minimize future conflicts.

**Comment by ryankask** [comment]
Okay, this has been rebased and should be good to go.

**Pull request merged**
