### PR TITLE
Trimmed search_results translation messages

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by felixxm** [comment]
@claudep Thanks :+1:  Can you push the updated English file to Transifex? or add me to the Django Team in Transifex.

**Comment by claudep** [comment]
Sure can you tell me your Transifex username?

**Comment by felixxm** [comment]
felixx

**Comment by claudep** [comment]
You are in!

**Comment by felixxm** [comment]
Thanks!

**Pull request merged**
