### PR TITLE
Fixed #868 -- Made English docs pages canonical for other languages.

### LINKED ISSUE #868: Google search results are showing French translations for English language links
Recently in my google searches for django things, French translations have been showing for English links.

For example, this search (https://www.google.com/search?client=ubuntu&channel=fs&q=django+refresh_from_db&ie=utf-8&oe=utf-8) resulted in https://docs.djangoproject.com/en/2.1/ref/models/instances/ being the displayed URL, but French is displayed.

Luckily, django methods are all in English, but could be an issue if I was searching for django concepts that did have a method associated.

2019-02-20-094421_1916x1053_scrot

### PR DESCRIPTION
**Pull request by m-aciek**
Closes #868.

Should I write a test for that change?

Adding as a draft as I didn't checked the changes locally yet.

### CODE REVIEW

**Comment by timgraham** [comment]
Seems fine to try. Please remove draft status. Doesn't seem like a test adds much.

**Comment by m-aciek** [comment]
@timgraham I've removed just now.

**Comment by tobiasmcnulty** [comment]
I'm not sure this is the appropriate fix. I posted a link to the Google docs here: https://github.com/django/djangoproject.com/issues/868#issuecomment-467695688

**Comment by timgraham** [comment]
Closing in favor of https://github.com/django/djangoproject.com/pull/872 (to be seen if it works).

**Pull request closed without merging**
