### PR TITLE
Fixed incorrect pluralization of LocalDjangoCommunity in admin - Issue Solved - #1739

### PR DESCRIPTION
**Pull request by arpan8925**
**Added verbose_name_plural = _("Local Django Communities") in the Meta class**

### CODE REVIEW

**Comment by arpan8925** [comment]
Hi , I need some help regarding this pull request. I am not sure if its merged , Its showing everything alright and auto merged in my Fork , and While did a pull request , its showing an error here.

I am actually a beginner to this Open source contributions and its my starting... Can you please guide ?

**Review by marksweb — APPROVED** [review]
This looks like it fixes #1739 to me 👍🏼

**Comment by marksweb** [comment]
> I hope this message finds you well. I am reaching out regarding Pull Request #1739. I am new to open-source contributions, and I am encountering some confusion with the status of this pull request.
> 
> It appears that everything looks correct and shows as auto-merged in my fork. However, when I submitted the pull request, it displayed an error here in the repository. I am unsure if it has been properly merged or if I need to take any further action.

So it might be worth you having a read of this; https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

You've clearly forked the repo, made a change and got that into a PR to fix an issue. But I notice you used the `main` branch. It's good practice to create branches specific to changes you wish to make. That way, if you were working on multiple, the'd be segregated in their own branches and you'd be free to update the main branch from the original (upstream) repository in order to keep working on new issues without mixing in the changes you've been making already.

**Comment by arpan8925** [comment]
Thanks a lot for pointing out the issue @marksweb . I did a new pull request by creating a new branch and from that branch 💖

**Comment by bmispelon** [comment]
Replaced by #1754

**Pull request closed without merging**
