### PR TITLE
Enhance windows cli examples

### PR DESCRIPTION
**Pull request by ramiro**
Changes to accompany django/django#8684 in case it gets accepted.

### CODE REVIEW

**Comment by timgraham** [comment]
Did you test it? I don't see the tabs when I try to preview with this branch and the corresponding django branch. Assuming it's not working and I'm not doing something wrong in test it, I would check if you've implemented enough so that the "json" builder that the website uses is using `ConsoleNode`.

**Comment by ramiro** [comment]
Yes. I did test it. I set things up as per the `README.rst` file and the animated GIF I [posted](https://code.djangoproject.com/ticket/28343#comment:5) to the ticket (http://imgur.com/3ce03UT) is recorded from the site running locally.

IIRC what could be happening to you is something that also bit me: The `update_docs` management command (`docs/management/commands/update_docs.py`) is hardcoded to  clone the Django source code at `$DJANGOPROJECT_DATA_DIR/djangodocs/sources/dev` (step 9 from the README instructions) but always using the master branch. 

The one needs

- To massage things manually a bit to get the brach you are trying to test there instead
- And then get the dir `_build/` and `_built/` subdirs in  `$DJANGOPROJECT_DATA_DIR/djangodocs/en/dev`re-populated. For this I used this script to replace the `./manage.py update_docs` part of step 9 (assuming you followed the example of using `~/.djangoproject` for $DJANGOPROJECT_DATA_DIR):

```
#!/bin/bash

SRC_DIR=~/.djangoproject/djangodocs/sources/dev/docs
PARENT_DIR=~/.djangoproject/djangodocs/en/dev
BUILD_DIR=$PARENT_DIR/_build

rm -rf $BUILD_DIR/djangohtml
mkdir -p $BUILD_DIR/djangohtml
sphinx-build -b djangohtml -D language=en $SRC_DIR $BUILD_DIR/djangohtml

rm -rf $BUILD_DIR/json
mkdir -p $BUILD_DIR/json
sphinx-build -b json -D language=en $SRC_DIR $BUILD_DIR/json

rsync --archive --delete --link-dest=$BUILD_DIR $BUILD_DIR/ $PARENT_DIR/_
```

**Comment by timgraham** [comment]
Yea, I did something similar but maybe I didn't get it quite right. I'll try again. Thanks!

**Comment by timgraham** [comment]
As per our IRC conversation some time ago, you need to make an update here to get this working, correct?

**Comment by ramiro** [comment]
Actually no in this PR but in the django/django#8684 one. I had forgot pushing the django/django@fc315d2b90319a2ce62e2f6a635cc0e87ef7e62e commit there which I already did and should fix the issue.

**Comment by timgraham** [comment]
Is "new-console-tabs.js" used? Otherwise, looks good.

**Comment by ramiro** [comment]
> Is "new-console-tabs.js" used? Otherwise, looks good.

Oops. It is actually the file supposed to be included. I've removed `console-tabs.js`  and `renamed `new-console-tabs.js` to `console-tabs.js`.

**Comment by ramiro** [comment]
Also, the lastes changes proposed to django/django to get FontAwesome (FA) served locally and upgraded to 5.0.x have no effect here as the djangoproject.com infrastructure already loads (most surely as part of the main web site functionality) FA from a CDN and we are reusing that.

It is currently using FA v4.2 but our usage is so minimal (the three Linux, macOS and Windows logos) that the version mismatch causes no compatibility issues.

Maybe we can think about update the FA version we use at some point in the future.

**Pull request merged**
