### PR TITLE
Add local Django community page

### PR DESCRIPTION
**Pull request by datur**
Issue: https://github.com/django/djangoproject.com/issues/1239

This change adds a new Local Django Communities page to the community area of the website. The aim is to list Local Django Communities around the world.

Community Page:
CleanShot 2023-06-12 at 11 47 52@2x

Local Django Community page:
CleanShot 2023-06-05 at 10 24 04@2x

### CODE REVIEW

**Comment by camilonova** [comment]
Please resolve the conflicts

**Comment by datur** [comment]
> Please resolve the conflicts

Conflicts resolved now 😄

**Comment by pauloxnet** [comment]
Do we need an additional package and SVG from Material icons to add this feature to the website?

**Comment by sabderemane** [comment]
>  Do we need an additional package and SVG from Material icons to add this feature to the website?

@pauloxnet I don't think so according what I've seen on the changes, I'll review the PR to double check

**Review by camilonova — APPROVED** [review]

**Review by sabderemane — APPROVED** [review]
Sorry for the late review. Thank you @datur for your contribution 🚀 

I've made some small changes to improve accessibility and added the case of if there's no data.

Welcome on board ⛵

**Review by sabderemane — APPROVED** [review]

**Pull request merged**
