### PR TITLE
Fixed #952 -- Added wallpaper designs in higher resolution

### LINKED ISSUE #952: Wallpapers are outdated  [new designs attached]
Hello,

I was browsing around and noticed [Wallpapers section](https://www.djangoproject.com/community/desktops/) where the biggest available wallpaper is 1680x1050 so I tried creating refreshed ones - see below. If you happen to like them I can provide other resolution variants or source files for Affinity Designer. 

django-wallpaper-gradient
django-wallpaper-solid

### PR DESCRIPTION
**Pull request by nemecek-filip**
@carltongibson hi! I am unable to modify the page that lists these because it uses the `flatpages` app and the content is stored in DjangoProjects.com database

### CODE REVIEW

**Comment by pauloxnet** [comment]
@nemecek-filip thanks for your PR.

I think it may be useful to also have the original file (eg: SVG) from which these images have been generated if it should be generated other versions in the future, in other formats (e.g. WebP) or make small variations (e.g. colors, fonts, ...).

In addition, I saw that the PNG files could be a smaller by optimizing them using one of the many lossless compression software (e.g. ImageOptim, Curtail, ...)

**Comment by nemecek-filip** [comment]
@pauloxnet thanks! Just commited optimized images and SVG one for possible future use.

**Review by pauloxnet — APPROVED** [review]

**Comment by pauloxnet** [comment]
> @pauloxnet thanks! Just commited optimized images and SVG one for possible future use.

Thanks, I approved the PR but I think we can wait for @carltongibson to review too.

**Comment by camilonova** [comment]
Looks awesome. Thank you so much!

**Pull request merged**
