### PR TITLE
fixed the recursion issue in tracedb models

### PR DESCRIPTION
**Pull request by Godvein**
[tracdb] Fix usage of time_property #1725

### CODE REVIEW

**Review by bmispelon — CHANGES_REQUESTED** [review]
Hi and thanks for the pull request!

The code changes look correct, but as I mentionned in the issue there should also be tests for all usage of `time_property` in the models. These tests should go in the file `tracdb/tests.py`.
I believe it should be possible to write the tests in a way that they don't have to interact with the database (and therefore use `SimpleTestCase` instead of `TestCase`). The tests could look like:

1) Instantiate a model with a set timestamp: `obj = TheModel(_timefield=1234)`
2) Check that the time property gives the expected results: `assertEqual(obj.timefiled, datetime(...))`

I hope that helps, if you have some questions feel free to ask here or on the official Discord (in the `#contributor-getting-started` channel).

**Comment by Godvein** [comment]
Sure sir, I will submit another PR for testcase

**Comment by bmispelon** [comment]
> Sure sir, I will submit another PR for testcase

No need for another PR, you can reuse this one by making a new commit and pushing it.

**Comment by Godvein** [comment]
i have pushed the necessary changes sir

**Review by bmispelon — CHANGES_REQUESTED** [review]
Thanks for the quick reply 👍🏻 

The tests look good overall, but could you:

1) Use the same test data for all tests;
2) Add a test for **all** usages of `time_property` (not just the ones you fixed, but also `Ticket`, `TicketChange`, ...)?

Thanks! 🚀

**Comment by Godvein** [comment]
Done sir I have pushed the changes

**Comment by Godvein** [comment]
hello sir my pull request is having test issue on run tox maybe its due to not making the required migrations after making changes in model.py i dont have the required technologies installed in my machine to make those migrations can you help me

**Comment by bmispelon** [comment]
> hello sir my pull request is having test issue on run tox maybe its due to not making the required migrations after making changes in model.py i dont have the required technologies installed in my machine to make those migrations can you help me

Hi,

It's not related to a migration, you used the wrong attribute name in some of the tests:
```
  ======================================================================
  ERROR: test_milestone_time_property (tracdb.tests.TimePropertyTest.test_milestone_time_property)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/runner/work/djangoproject.com/djangoproject.com/tracdb/tests.py", line 280, in test_milestone_time_property
      obj = Milestone(_time=self.test_data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/runner/work/djangoproject.com/djangoproject.com/.tox/py312-tests/lib/python3.12/site-packages/django/db/models/base.py", line 567, in __init__
      raise TypeError(
  TypeError: Milestone() got unexpected keyword arguments: '_time'
  
  ======================================================================
  FAIL: test_attachment_time_property (tracdb.tests.TimePropertyTest.test_attachment_time_property)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/runner/work/djangoproject.com/djangoproject.com/tracdb/tests.py", line 301, in test_attachment_time_property
      self.assertEqual(obj.time, expected_time)
  AssertionError: datetime.datetime(1970, 1, 1, 0, 20, 34, 567890, tzinfo=datetime.timezone.utc) != datetime.datetime(2009, 2, 13, 23, 31, 30)
  
  ======================================================================
  FAIL: test_revision_time_property (tracdb.tests.TimePropertyTest.test_revision_time_property)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/runner/work/djangoproject.com/djangoproject.com/tracdb/tests.py", line 289, in test_revision_time_property
      self.assertEqual(obj.time, expected_time)
  AssertionError: datetime.datetime(1970, 1, 1, 0, 20, 34, 567890, tzinfo=datetime.timezone.utc) != datetime.datetime(2009, 2, 13, 23, 31, 30)
  
  ======================================================================
  FAIL: test_ticket_time_property (tracdb.tests.TimePropertyTest.test_ticket_time_property)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/runner/work/djangoproject.com/djangoproject.com/tracdb/tests.py", line 308, in test_ticket_time_property
      self.assertEqual(ticket.time, expected_time)
  AssertionError: datetime.datetime(1970, 1, 1, 0, 20, 34, 567890, tzinfo=datetime.timezone.utc) != datetime.datetime(2009, 2, 13, 23, 31, 30)
  
  ======================================================================
  FAIL: test_ticketchange_time_property (tracdb.tests.TimePropertyTest.test_ticketchange_time_property)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/runner/work/djangoproject.com/djangoproject.com/tracdb/tests.py", line 315, in test_ticketchange_time_property
      self.assertEqual(ticket_change.time, expected_time)
  AssertionError: datetime.datetime(1970, 1, 1, 0, 20, 34, 567890, tzinfo=datetime.timezone.utc) != datetime.datetime(2009, 2, 13, 23, 31, 30)
  
  ======================================================================
  FAIL: test_version_time_property (tracdb.tests.TimePropertyTest.test_version_time_property)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/runner/work/djangoproject.com/djangoproject.com/tracdb/tests.py", line 322, in test_version_time_property
      self.assertEqual(version.time, expected_time)
  AssertionError: datetime.datetime(1970, 1, 1, 0, 20, 34, 567890, tzinfo=datetime.timezone.utc) != datetime.datetime(2009, 2, 13, 23, 31, 30)
  
  ======================================================================
  FAIL: test_wiki_time_property (tracdb.tests.TimePropertyTest.test_wiki_time_property)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/runner/work/djangoproject.com/djangoproject.com/tracdb/tests.py", line 295, in test_wiki_time_property
      self.assertEqual(obj.time, expected_time)
  AssertionError: datetime.datetime(1970, 1, 1, 0, 20, 34, 567890, tzinfo=datetime.timezone.utc) != datetime.datetime(2009, 2, 13, 23, 31, 30)
  
  ----------------------------------------------------------------------
```

**Comment by bmispelon** [comment]
The issue with your tests is that you can't use `utcfromtimestamp` (Trac uses a different timestamp system).

My advice is to use `1_000_000` (1 million) as a timestamp value, and `datetime(1970,1,1,0,0,1)` (Januar 1st 1970, 1 second past midnight) as the corresponding expected date.

**Comment by bmispelon** [comment]
Hi,

It looks like the tests are failing again, probably because the expected value does not have timezone information. You're also missing tests for `Ticket.changetime` and `Milestone.completed`.

I think this could be simplified into a single test method using `subTest`:
```
    def test_time_property_on_all_fields(self):
        for model_class, field_name, property_name in [
            (Ticket, "_time", "time"),
            (Ticket, "_changetime", "changetime"),
            (Version, "_time", "time"),
            (Milestone, "_due", "due"),
            (Milestone, "_completed", "completed"),
            (Revision, "_time", "time"),
            (Wiki, "_time", "time"),
            (Attachment, "_time", "time"),
        ]:
            with self.subTest(model=model_class, field=field_name):
                obj = model_class(**{field_name: 1_000_000})
                self.assertEqual(
                    getattr(obj, property_name),
                    datetime(1970, 1, 1, 0, 0, 1, tzinfo=UTC)
                )
```

**Comment by Godvein** [comment]
Hi sir,
sorry for the issues. I will implement your solution, Thanks for the help

**Comment by Godvein** [comment]
Thank you sir for helping me solve the PR test issues and making my first contribution in this organisation possible

**Pull request merged**
