### PR TITLE
Enable profiling of transactions in Sentry

### PR DESCRIPTION
**Pull request by tobiasmcnulty**
https://docs.sentry.io/platforms/python/profiling/#enable-profiling

### CODE REVIEW

**Comment by bmispelon** [comment]
The document you linked states that:

> The profiles_sample_rate setting is relative to the traces_sample_rate setting.

So I my math is right, that means only 1% of transactions will be profiled. Was that the intent?

**Comment by tobiasmcnulty** [comment]
@bmispelon Excellent catch! I missed that. I suppose I intended to set `profiles_sample_rate=1.0`, but I am open to any suggestions.

**Comment by bmispelon** [comment]
It's unclear to me what kind of overhead the profiling has.
I think you'll be the one living with the consequences, as I'm not on the ops team (yet? 🙃) so it's fair if you get to decide. 10% seems as good a percent as any. 👍🏻

**Review by bmispelon — APPROVED** [review]

**Comment by tobiasmcnulty** [comment]
Thanks for the review! This has been deployed.

**Pull request merged**
