### PR TITLE
Add roadmap graphic

### PR DESCRIPTION
**Pull request by nicktimko**
PR for #668. A little cleaner, thoughts?

"styling" is just a `max-width:100%`, hopefully Kosher enough. In-browser:

image

### CODE REVIEW

**Comment by MarkusH** [comment]
Sweet. Looks nice! :+1:

**Comment by timgraham** [comment]
About the graphic, I wonder if the fact that "2016" appears above the December line might cause confusion and give the impression that it means "December 2016."

A few edits:
```diff
diff --git a/djangoproject/templates/releases/download.html b/djangoproject/templates/releases/download.html
index 128acf9..ff515cf 100644
--- a/djangoproject/templates/releases/download.html
+++ b/djangoproject/templates/releases/download.html
@@ -1,5 +1,5 @@
 {% extends "base.html" %}
-{% load fundraising_extras release_notes %}
+{% load fundraising_extras release_notes staticfiles %}
 
 {% block sectionid %}download{% endblock %}
 {% block title %}Download Django{% endblock %}
@@ -64,11 +64,11 @@
   <p>Certain feature releases will be designated as <strong>long-term support
     (LTS) releases</strong>. These releases will get security and data loss
     fixes applied for a guaranteed period of time, typically three years.</p>
+  <p>See the <a href="https://docs.djangoproject.com/en/dev/internals/release-process/#supported-versions">
+    supported versions policy</a> for detailed guidelines about what fixes will be backported.</p>
 
   <img src="{% static "img/release-roadmap.png" %}" style="max-width:100%;" alt="">
 
-  <p>See the <a href="https://docs.djangoproject.com/en/dev/internals/release-process/#supported-versions">
-    supported versions policy</a> for detailed guidelines about what fixes will be backported.</p>
   <table class='django-supported-versions'>
       <tr>
         <th>Release Series</th>
```

**Comment by nicktimko** [comment]
I had the figure right after the paragraph about the "guaranteed period of time" to follow on right then. Plus I personally don't like the figure right with the table ;)

I thought about interpreting the labeled December line as "December 2016" but I think if you're looking at the "December", you'd also see the "April, August" sequence which should make it clear. I'm not going for perfect accuracy: the figure is more to convey how non-LTS and LTS releases line up (e.g. only one gets full support at any one time, and there is a 1 year period to transition from LTS to LTS.

I'll add in the load staticfiles.

**Comment by timgraham** [comment]
Maybe we could insert `<hr>` or some CSS border between the table and the graphic. I don't think stranding the paragraph about what fixes will be backported makes much sense.

**Comment by timgraham** [comment]
merged in 3d060e49559e6a2c69bdcb073f5453721b0cccb6, thanks!

**Pull request closed without merging**
