### PR TITLE
Add 'data' dir to gitignore

### PR DESCRIPTION
**Pull request by adamchainz**
This is created by `docker-compose up -d` which sets `DJANGOPROJECT_DATA_DIR=./data`.

### CODE REVIEW

**Review by bhavanasam — APPROVED** [review]

**Review by carltongibson — APPROVED** [review]
Yep, OK.

**Comment by carltongibson** [comment]
[CI did pass despite no notification](https://travis-ci.org/github/django/djangoproject.com/builds/772231012?utm_source=github_status&utm_medium=notification)

**Comment by adamchainz** [comment]
Another one for a github actions conversion?

**Comment by carltongibson** [comment]
If you have bandwidth, yes super please. 🥇

**Pull request merged**
