### PR TITLE
Stopped building docs for unsupported versions.

### PR DESCRIPTION
**Pull request by felixxm**
This should make bumping Sphinx version much easier.

### CODE REVIEW

**Comment by felixxm** [comment]
@claudep Can you take a look?

**Comment by claudep** [comment]
Maybe add this as a command option? In the general case, I think it's fine to not run updates for unsupported versions. However, if you completely wipe the built docs, having the older docs still at hand might still be useful, so in this case, being able to force rebuilding old docs might still be handy.

**Comment by felixxm** [comment]
> Maybe add this as a command option? In the general case, I think it's fine to not run updates for unsupported versions. However, if you completely wipe the built docs, having the older docs still at hand might still be useful, so in this case, being able to force rebuilding old docs might still be handy.

Agreed, I think we can reuse the `force` option for this.

**Comment by felixxm** [comment]
@claudep Thanks :+1:

**Pull request merged**
