### PR TITLE
use same datetime now

### PR DESCRIPTION
**Pull request by phodal**

### CODE REVIEW

**Comment by bmispelon** [comment]
Hi,

This looks like it makes sense, but what problem does it fix?

Thanks.

**Comment by phodal** [comment]
Hi @bmispelon ,

   I don't setup local env to run test for this case, to many things to do. And for some reason in China, I couldn't visit Travis CI. So, maybe you can do it yourself.

**Comment by bmispelon** [comment]
I'm not sure why you closed the pull request. Your proposal seems good and I'd be happy to merge it but I'm interested to know the reason behind it (is it just a cleanup or does it fix a bug for example?).

I looked at the failure on Travis but it seems unrelated to your change.

**Comment by phodal** [comment]
Hi @bmispelon, 

   For my case, I try to use blog app for my project in Django 1.8. And maybe it's a bug fix in *render_month_links* method

    @register.inclusion_tag('blog/month_links_snippet.html')
    def render_month_links():
        return {
            'dates': Entry.objects.published().datetimes('pub_date', 'month', order='DESC'),
        }

**Comment by bmispelon** [comment]
I see, that makes sense.

It might be tricky, but do you think you could write a testcase that shows the existence of the bug (and it would also show that the bug is fixed with your proposed change)?

I will reopen your pull request in the meantime if that's ok with you.
Thanks!

**Comment by timgraham** [comment]
merged in fe5699f29bee2d7a95f716070632ee6e589d334a, thanks!

**Pull request closed without merging**
