### PR TITLE
Fixed #1216 -- Added reCaptcha to DSF contact form

### LINKED ISSUE #1216: Add Google reCAPTCHA to DSF Contact Form
We get a ton of spam on a daily basis through the [DSF Contact Form](https://www.djangoproject.com/contact/foundation/), which makes it really hard to find actual messages (they get lost in a sea of spam messages). The form uses Akismet to filter out spam, but it doesn't seem to be very effective.

Maybe using something like Google reCAPTCHA could help us to reduce the spam? I'm open to other solutions as well, as long as we can achieve a similar result.

I was going to try doing this myself, but I guess opening an issue and seeing if someone else wants to grab it is a good idea as well.

### PR DESCRIPTION
**Pull request by CuriousLearner**
Despite using Akismet, DSF is receiving a lot of spam messages. We are adding Google reCaptcha V3 to the DSF Contact Form to reduce spam messages along with Akismet.

### CODE REVIEW

**Review by zanderle — APPROVED** [review]
LGTM 👍

Thank you so much :)

**Review by pauloxnet — APPROVED** [review]

**Comment by CuriousLearner** [comment]
Thank you for your reviews :)

**Comment by pauloxnet** [comment]
@CuriousLearner thanks for your contribution but it would be a good rule that PRs are not merged by the same person who opens them. I saw that you indicated Carlton as a reviewer and I didn't merged it because I imagined you wanted to wait for him. Next time wait for someone to merge your PRs please.

**Comment by carltongibson** [comment]
Thanks all. I deployed this, and it looks like the recaptcha is loading and validating (at least pre-submission) as expected. 👍 (@zanderle I don't know if you want to try a manual test just to 100% confirm?)

**Comment by zanderle** [comment]
@carltongibson Just tested, and the form works as expected. We'll keep an eye on spam and see after a few days if this did the trick. Thank you all! The whole board will be very thankful for this 😄  🎉

**Comment by CuriousLearner** [comment]
@pauloxnet ok. Sure thing. I'll wait for someone else to merge my PR. Since I got two approvals, I thought it was ok to merge. I will definitely keep this in mind.

Thank you!

**Pull request merged**
