### PR TITLE
Fixed #1204 -- Use websearch type for search query

### LINKED ISSUE #1204: Use websearch type for search query
Use [websearch](https://www.postgresql.org/docs/12/textsearch-controls.html#TEXTSEARCH-PARSING-QUERIES) type for search query _(to permit control on user search)_

### PR DESCRIPTION
**Pull request by pauloxnet**
Part of #1031

### CODE REVIEW

**Review by CuriousLearner — APPROVED** [review]
Looks good. Thanks 👍🏼

**Comment by CuriousLearner** [comment]
Hey @carltongibson 

I have the access to merge now. Though I've a few questions before I merge:

- I observed older commit messages, and a few of them have the PR no appended to them, and a lot of them do not. Do we have a preference here?
- For merging a PR, I think `squash & merge` strategy is preferred with commit messages following the format of Django source code. Is that correct?

**Comment by carltongibson** [comment]
So Squash and Merge appends the PR number to the title, unless you edit it. That's OK, but I don't think we have an official house style, as we do for django/django. @pauloxnet has given this a `Fixed #1204` prefix, so I think that's good enough.

**Comment by CuriousLearner** [comment]
Thanks @carltongibson 

That sounds good to me.

Thanks for the PR @pauloxnet

**Pull request merged**
