### PR TITLE
Fix color contrast

### LINKED ISSUE #974: Check colours for accessibility / WCAG compliance
There are a couple of areas where the current colour contrasts between fonts and backgrounds fail the WCAG 2.0 colour contrast accessibility guidelines on the djangoproject.com pages.
It's mostly to do with the bright green compared with white/white-ish colours:

### Green on gray, [contrast 2.79](https://contrast-ratio.com/#rgb%2832%2C%20170%2C%20118%29-on-%23f8f8f8)

Fails all checks, mostly in use on sidebars.
DeepinScreenshot_select-area_20200129111742

### Bright green on less bright green, [contrast 2.02](https://contrast-ratio.com/#%23C9F0DD-on-%2344b78b)

Fails all checks, it's in use in title areas.
DeepinScreenshot_select-area_20200129111856

### Bright green on dark green, [contrast 4.05](https://contrast-ratio.com/#%2344B78B-on-%230c4b33)

This would be okay with 14pt+ instead of the current ~10pt, but 14pt is unreasonably huge.

DeepinScreenshot_select-area_20200129112047

### Green on green, [contrast 2.43](https://contrast-ratio.com/#rgb%2843%2C%20140%2C%20103%29-on-%230c4b33)

Fails all checks, is hard to read even for me.

DeepinScreenshot_select-area_20200129112333

### White on green, [contrast 2.5](https://contrast-ratio.com/#white-on-%2344B78B)

Sadly, this isn't even WCAG compliant in large/bold fonts, and we use it on all of our buttons, etc.
DeepinScreenshot_select-area_20200129112526

## Next steps

For me (good vision, good screen) some of the completely failing combinations are perfectly easy to read, like the white font on bright green buttons – but that's the point of accessibility guidelines, they're not for people with good vision and good screens.

Since this impacts a lot of the djangoproject.com page, especially with the bright green being so prevalent, I'm not sure how to proceed here, but I wanted to document the issue to start a conversation about it.

### PR DESCRIPTION
**Pull request by xi**
Fixes #974. Note that it changes brand colors.

I went for a contrast ratio of 3:1, which is the absolute minimum according to [WCAG](https://www.w3.org/TR/WCAG21/#contrast-minimum). It is debatable whether this is sufficient to pass AA, but I didn't want to change too much.

### CODE REVIEW

**Review by thibaudcolas — CHANGES_REQUESTED** [review]
👋 I’ve had a brief look at this, I don’t think it goes far enough unfortunately. 3 is the minimum contrast ratio for large text, disabled forms controls, and non-text UI elements. For all other text, we need to aim for 4.5:1 at a minimum.

I’ll follow up on #974 since there is a fair amount of discussion there.

**Comment by xi** [comment]
@thibaudcolas I understand that this could be better in terms of accessibility, but as explained above, I tried to strike a balance between accessibility and keeping the brand colors. Do you think we should change the brand colors completely? If so, I guess there is someone who would need to authorize that change. Do you know who that would be?

**Comment by thibaudcolas** [comment]
Hey @xi, good question. I have little to no background on this so this is just my opinion – I think the dark green should stay, I doubt all the other colors matter that much. We want to preserve the brand identity of Django no matter what color ends up being used, so I’d say it’s better to do one ”big-bang” change to get to full compliance and not risk having to do further tweaks.

The only color I would consider a "brand" color for Django is this dark green, documented on https://www.djangoproject.com/community/logos/, but if you start looking at Django’s usage on that green:

- The PNG and EPS logos on that page actually use a different shade, #113E2E. It’s only the SVG logo that uses the documented #092E20.
- That official shade of green isn’t used at all on the website (!)

**Comment by xi** [comment]
I would be open for making more drastic changes, but not without any "official" clearance on changing brand colors. @carltongibson can you give us that or ping the relevant person?

**Comment by thibaudcolas** [comment]
@xi can you clarify which colors qualify as brand colors to you? The only one documented on https://www.djangoproject.com/community/logos/ isn’t even used on the site.

**Comment by carltongibson** [comment]
Hi both. Thanks for your work here. 

I've posted back to the mailing list thread for establishing the accessibility team, to ask about this question, and if we can get input from the design team on such questions going forward. (I think it's probably an easy resolve for someone in the know...) — Let's see how that goes. 

https://groups.google.com/g/django-developers/c/FsBrNGTxvCA

**Comment by xi** [comment]
> can you clarify which colors qualify as brand colors to you?

The changes required here would be very noticeable to people who regularly visit djangoproject.com. Even if they don't technically qualify as brand colors, they are still an important part of django's visual identity.

**Comment by pauloxnet** [comment]
> I think it's actually better to wait for #1213 as it adds variables for colours, so this PR can be simplified.

@knyghty @xi @thibaudcolas  the PR #1213 has been merged so . Do you think you can now rebase this PR and continue working on it?

**Comment by xi** [comment]
See #1233 for an updated version.

**Pull request closed without merging**
