### PR TITLE
Moved unsupported releases to a separate table on downloads page.

### PR DESCRIPTION
**Pull request by chicheng**
Please let me know if you prefer squashed single commit for these changes.

### CODE REVIEW

**Comment by carltongibson** [comment]
Current Master: 

current master

Suggested Changes: 

Updated

**Comment by chicheng** [comment]
Thanks for the review @carltongibson . I have updated the html file accordingly.

**Comment by carltongibson** [comment]
Hi @chicheng — sorry for the hold-up here. Do you fancy rebasing this, and we'll see if we can proceed. Thanks.

**Comment by chicheng** [comment]
No worries, I'll update the files this weekend.

> 
> 
> Hi @chicheng — sorry for the hold-up here. Do you fancy rebasing this, and we'll see if we can proceed. Thanks.

**Comment by chicheng** [comment]
Hi @carltongibson Sorry for missed this ticket. I just rebased the changes and force pushed. (It seems the CI is failing on a migration file not exists in the repository `foundation/migrations/0002_auto_20210109_0729.py` ?)

**Comment by carltongibson** [comment]
Ok thanks @chicheng. I'll take a look next week

**Review by carltongibson — APPROVED** [review]
Hi @chicheng — sorry for the slow follow-up here. 

I've rebased and reviewed again. I still like this. 

Proposed change:

Screenshot 2021-03-25 at 15 26 51

@felixxm Can I just ask for your opinion, so at least there's two of us? Thanks.

**Comment by felixxm** [comment]
@chicheng Thanks :+1:

**Pull request merged**
