### PR TITLE
Added missing mocks in fundraising tests.

### PR DESCRIPTION
**Pull request by timgraham**
Django 1.9 gives "ValueError: Failed to insert expression"
without these fixes.

### CODE REVIEW

**Comment by timgraham** [comment]
@jarshwah, this resolves the confusing traceback I pinged you about earlier. I think it's probably not an issue to block the alpha, but possibly the error message could be improved for this type of user error.
```
======================================================================
ERROR: test_make_donation_with_existing_hero (fundraising.tests.TestPaymentForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/mock.py", line 1125, in patched
    return func(*args, **keywargs)
  File "/home/tim/code/djangoproject.com/fundraising/tests.py", line 329, in test_make_donation_with_existing_hero
    donation = form.make_donation()
  File "/home/tim/code/djangoproject.com/fundraising/forms.py", line 272, in make_donation
    donation=donation,
  File "/home/tim/code/django/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/code/django/django/db/models/query.py", line 401, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/tim/code/django/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/tim/code/django/django/db/models/base.py", line 728, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/tim/code/django/django/db/models/base.py", line 812, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/tim/code/django/django/db/models/base.py", line 851, in _do_insert
    using=using, raw=raw)
  File "/home/tim/code/django/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/code/django/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/tim/code/django/django/db/models/sql/compiler.py", line 1063, in execute_sql
    for sql, params in self.as_sql():
  File "/home/tim/code/django/django/db/models/sql/compiler.py", line 1023, in as_sql
    for obj in self.query.objs
  File "/home/tim/code/django/django/db/models/sql/compiler.py", line 1023, in <listcomp>
    for obj in self.query.objs
  File "/home/tim/code/django/django/db/models/sql/compiler.py", line 1022, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/tim/code/django/django/db/models/sql/compiler.py", line 957, in prepare_value
    'can only be used to update, not to insert.' % (value, field)
ValueError: Failed to insert expression "<MagicMock name='create().id.resolve_expression()' id='139633074508184'>" on fundraising.Payment.stripe_charge_id. F() expressions can only be used to update, not to insert.
```

**Comment by jarshwah** [comment]
I'm not sure I fully understand the error condition here. Taking mocks out of the equation, are we talking about the equivalent of ```Model.objects.create(x=F('y'))```?

If so, then the error message seems mostly OK, unless we went with something a little more terse and direct:

> Failed to insert expression "<MagicMock name='create().id.resolve_expression()' id='139633074508184'>". F() expressions can not be used to create new instances.

The major failing above is that MagicMock doesn't have a great repr, which hurts the readability quite a bit. 

Have you got any suggestions?

**Comment by timgraham** [comment]
I think the thing that confused me is "F() expressions can only be used to update, not to insert." when we don't have an F expression here.

**Comment by jarshwah** [comment]
Ok, I think I understand what has happened. The mock has ended up being resolved to a `Col()` reference, and it is the presence of a `Col` that triggers the warning seen above. `Col` isn't public though, so the proxy for Col, `F()`, is used to return the error.

I haven't looked into why the mock is being resolved to a Col as yet. I'll create a ticket on trac.

**Pull request merged**
