### PR TITLE
Updated download link to point to tar.gz instad of zip archive.

### PR DESCRIPTION
**Pull request by timgraham**
Refs Trac ticket #24761

### CODE REVIEW

**Comment by bmispelon** [comment]
Can windows open gzipped tarballs natively? If not, I'm worried that change might be a little too agressive for windows users.

**Comment by jezdez** [comment]
@bmispelon I haven't used it, but AFAIK Python on Windows can do that, Python ships with both a tarfile and gzip library. brb testing..

**Comment by bmispelon** [comment]
Our own documentation (https://docs.djangoproject.com/en/dev/topics/install/#installing-an-official-release-manually) recommends bsdtar (command line) or 7-zip (GUI) so it might not be such a big problem after all.

**Comment by jezdez** [comment]
I tried on Python 3.4 on Windows 7 just now and it worked.

**Pull request merged**
