### PR TITLE
Added PyCharm banners for 2022 fundraiser.

### PR DESCRIPTION
**Pull request by carltongibson**
Refs 8cfe240d8d1e60f8724aa8303f7afc68a01895ce

Preparing for fundraiser. 

- [x] Confirmation from @wsvincent 
- [x] Deploy on June 1?

### CODE REVIEW

**Review by felixxm — APPROVED** [review]
@carltongibson Thanks :+1:

**Comment by wsvincent** [comment]
Yes from me. For June 1. I am awaiting confirmation on Landing Page which I should have by end of day today. Otherwise ready to go. I will do blog post, Tweet as DSF, etc tomorrow.

So please wait for me to confirm the link but otherwise all good. Thank you!

**Comment by wsvincent** [comment]
Still awaiting the proper link. Hasn't come yet so wait please until I receive it for real. JetBrains is translating various things on their end at the moment.

**Review by wsvincent — APPROVED** [review]
Yes, looks good. That URL is correct. Should go live in about an hour, 2pm CEST. Currently it redirects to the PyCharm homepage but will go to the dedicated Django page shortly. JetBrains is finishing the translations but plan to launch it then and related social media/blog post on their end at 4pm CEST.

**Pull request merged**
