### PR TITLE
Extend PyCharm Campaign

### PR DESCRIPTION
**Pull request by frankwiles**
We're going to extend the PyCharm campaign a few days.  This replaces the existing image on Fundraising with the new accurate end date. 

Please merge and deploy as soon as possible thanks!

### CODE REVIEW

**Comment by timgraham** [comment]
Is there a reason not to replace the existing image rather than adding another one?

**Comment by frankwiles** [comment]
I was thinking of browser caches but I see we don't see any serious headers in that vein.  I'll adjust it.

**Comment by frankwiles** [comment]
All updated.

**Comment by timgraham** [comment]
Merged in cdc1b51387e68f1bfbc7f7b747a873fa8f62cabd.

**Pull request closed without merging**
