### PR TITLE
Added list of Django Core Developers.

### PR DESCRIPTION
**Pull request by felixxm**
@wsvincent Can the board take a look?

### CODE REVIEW

**Comment by felixxm** [comment]
image

**Comment by glasnt** [comment]
The "dsf-board" team is out of date to the current board fyi (I got tagged into this PR but I haven't been on the board for years)

**Comment by felixxm** [comment]
> The "dsf-board" team is out of date to the current board fyi (I got tagged into this PR but I haven't been on the board for years)

Thanks, I removed former members.

**Comment by wsvincent** [comment]
Yes this looks good. Board has discussed. Apologies for being so late in response @felixxm.

**Comment by felixxm** [comment]
@wsvincent Thanks for checking :+1:

**Pull request merged**
