### PR TITLE
Add back to top link in documentation

### PR DESCRIPTION
**Pull request by HanaPoulpe**
Issue: https://github.com/django/djangoproject.com/issues/203

image

### CODE REVIEW

**Review by knyghty — APPROVED** [review]
LGTM, thank you! 🚀

**Comment by sabderemane** [comment]
@HanaPoulpe can you please check for the merge conflicts?

**Comment by HanaPoulpe** [comment]
> @HanaPoulpe can you please check for the merge conflicts?

Conflicts solved and pushed, ready for review and merge

**Review by sabderemane — CHANGES_REQUESTED** [review]
Capture d’écran 2023-06-16 à 01 57 45

This might be due to a class or a style missing (I didn't check deeply), but there is a dot from the `ul li` list appearing, otherwise looks good!

**Comment by HanaPoulpe** [comment]
> Capture d’écran 2023-06-16 à 01 57 45
> 
> This might be due to a class or a style missing (I didn't check deeply), but there is a dot from the `ul li` list appearing, otherwise looks good!

I've checked on my local and can't replicate the issue, can you confirm the browser you are using? This is a screenshot from `Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0`

image

Also making sure: did you rebuild css for testing?

**Review by sabderemane — APPROVED** [review]
Thank you for your contribution @HanaPoulpe ! 

Welcome on board ⛵

**Pull request merged**
